# -*- coding: utf-8 -*-
"""homework_9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0NGJ80lcXnO6HUsDo9hRykzOkRqpVqb
"""

import pandas as pd

df = pd.read_csv('sample_data/california_housing_train.csv')

df.head()

#Задача 40: Работать с файлом california_housing_train.csv, который находится в папке sample_data. 
#Определить среднюю стоимость дома, где кол-во людей от 0 до 500 (population).

round(df[df['population'] <= 500]['median_house_value'].mean(), 3)

#Задача 42: Узнать какая максимальная households в зоне минимального значения population.

df[df['population'] == df['population'].min()]['households'].max()